wp:
  name: wpapp
  labels:
    app: wp
    env: dev
    stack: wordpress
  image:
    repository: krutipatel15/nginx-act-3
    tag: v4
    pullPolicy: Always
  replicas: 1
  containerPorts:
      http: 80
